[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2.6"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~10.0.0"

[[override]]
  name = "github.com/golang/glog"
  source = "github.com/kubermatic/glog-logrus"

[prune]
  go-tests = true
  unused-packages = true
