apiVersion: v1
data:
  config.yaml: |
    interval: 1h
    pod_rules_labels_filled_in:
    - name: Check if label app is active on every pod
      labels:
      - app
      filter:
        namespaces: "!kube-system"
    pod_rules_limits_filled_in:
    - name: Checks if limits are filled in everywhere
      filter:
        namespaces: "!kube-system"
    pod_rules_requests_filled_in:
    - name: Checks if requests are filled in everywhere
    deployment_rules_replicas_minimum:
    - name: Checks that al Deployments have a minimum of 2 replicas
      minimum_replicas: 2
      filter:
        exclude_namespaces:
        - kube-system
    stateful_set_rules_replicas_minimum:
    - name: Checks that al StatefulSets have a minimum of 2 replicas
      minimum_replicas: 2
      filter:
        exclude_namespaces:
        - kube-system
kind: ConfigMap
metadata:
  name: kube-conformity