apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-conformity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-conformity
  template:
    metadata:
      labels:
        app: kube-conformity
    spec:
      serviceAccountName: kube-conformity
      containers:
      - name: kube-conformity
        image: sdehaes/kube-conformity:latest
        args:
        - --config-location=/etc/config/config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
          - containerPort: 8000
            name: web
        readinessProbe:
          httpGet:
            port: web
            path: /healthz
        livenessProbe:
          httpGet:
            port: web
            path: /healthz
      volumes:
      - name: config-volume
        configMap:
          name: kube-conformity